update docker-compose.yml

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,4 +1,43 @@
-version: '2.1'
+# Adapted from official docker-compose.yaml
+# https://airflow.apache.org/docs/apache-airflow/2.5.1/docker-compose.yaml
+
+version: '3'
+
+x-airflow-common:
+  &airflow-common
+  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
+  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
+  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
+  build: .
+  env_file:
+    - ./resources/dev_variables.env
+    - ./resources/dev_connections.env
+  environment:
+    &airflow-common-env
+    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
+    AIRFLOW_DATABASE_URL: mysql://root:secret@db:3306/airflow
+    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
+    AIRFLOW_AUTHENTICATE: False
+    AIRFLOW_BROKER_URL: redis://redis:6379/0
+    AIRFLOW_RESULT_URL: redis://redis:6379/0
+    AIRFLOW_FLOWER_PORT: 5555
+    AIRFLOW_SECRET_KEY: 000000000000000000000000000000000000000000=
+    URL: http://localhost:8080
+    PORT: 8080
+    DEPLOY_ENVIRONMENT: dev
+    DEVELOPMENT: 1
+  volumes:
+    - ./dags:/opt/airflow/dags
+    - ./logs:/opt/airflow/logs
+    - ./plugins:/opt/airflow/plugins
+    - ./resources/dev_webserver_config.py:/opt/airflow/webserver_config.py
+  user: "${AIRFLOW_UID:-50000}:0"
+  depends_on:
+    &airflow-common-depends-on
+    redis:
+      condition: service_healthy
+    db:
+      condition: service_healthy
 
 services:
   db:
@@ -8,100 +47,200 @@ services:
     image: mysql:5.7
     ports:
       - '3306:3306'
-    # command: ['--explicit_defaults_for_timestamp=1', '--character-set-server=utf8mb4']
     command: ['--explicit_defaults_for_timestamp=1']
     environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: airflow
+    healthcheck:
+      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
+      timeout: 20s
+      retries: 10
 
   redis:
     image: redis:3.2
-
-  app:
-    build:
-      context: .
-      dockerfile: Dockerfile
-    restart: "no"
-    volumes:
-      - $PWD:/app
-      - $PWD/dev_webserver_config.py:/app/webserver_config.py
-      # mount a dummy file to google application credentials, if not provided
-      - ${GOOGLE_APPLICATION_CREDENTIALS:-./.add_credentials.md}:/tmp/.credentials
-    command: "true"
-    # Environment variables, exports, and substitution:
-    #   https://docs.docker.com/compose/environment-variables/
-    # Setting connection strings from environment variables:
-    #   https://airflow.apache.org/howto/connection/index.html#creating-a-connection-with-environment-variables
-    # Non-intuitive quoting behavior in docker-compose due to list syntax and yaml parsing:
-    #   https://github.com/docker/compose/issues/2854#issuecomment-433592364
-    environment:
-      - AWS_SECRET_ACCESS_KEY
-      - AWS_ACCESS_KEY_ID
-      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/.credentials
-      - PORT=8000
-      - DEPLOY_ENVIRONMENT=dev
-      - DEVELOPMENT=1
-      - AIRFLOW_HOME=/app
-      - AIRFLOW_AUTHENTICATE=False
-      - AIRFLOW_AUTH_BACKEND=airflow.contrib.auth.backends.password_auth
-      - AIRFLOW_BROKER_URL=redis://redis:6379/0
-      - AIRFLOW_RESULT_URL=redis://redis:6379/0
-      - AIRFLOW_FLOWER_PORT=5555
-      - AIRFLOW_DATABASE_URL=mysql://root:secret@db:3306/airflow
-      - AIRFLOW__CORE__FERNET_KEY=0000000000000000000000000000000000000000000=
-      - AIRFLOW_SECRET_KEY=000000000000000000000000000000000000000000=
-      - AIRFLOW_SMTP_FROM=telemetry-alerts@airflow.dev.mozaws.net
-      - AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False
-      - AIRFLOW_EMAIL_BACKEND=airflow.macros.log_email_backend.log_email_backend
-      - AIRFLOW__KUBERNETES__IN_CLUSTER=False
-      - URL=http://localhost:8000
-      # URL-encoded dummy connections; note that we define some other connections
-      # in the bin/run script
-      - AIRFLOW_CONN_ADM_SFTP=ftp://myname:mypassword@myhost.com:8000?known_hosts=myhost.com+AAAABBBBB
-      # TODO(hwoo) - improve developer workflow by not loading all dags
-      # - AIRFLOW__CORE__DAGS_FOLDER=$AIRFLOW_HOME/devdags
-
-  web:
-    extends:
-      service: app
+    expose:
+      - 6379
+    healthcheck:
+      test: [ "CMD", "redis-cli", "ping" ]
+      interval: 5s
+      timeout: 30s
+      retries: 50
     restart: always
+
+
+  airflow-webserver:
+    <<: *airflow-common
+    command: webserver
     ports:
-      - "8000:8000"
+      - 8080:8080
+    healthcheck:
+      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
     depends_on:
-      - app
-    links:
-      - db
-      - redis
-    command: web
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
 
-  worker:
-    extends:
-      service: app
-    restart: always
-    mem_limit: "4294967296"
-    ports:
-      - "8793:8793"
-    links:
-      - db
-      - redis
-    command: worker
-
-  scheduler:
-    mem_limit: "4294967296"
-    extends:
-      service: app
-    restart: always
-    links:
-      - db
-      - redis
+  airflow-scheduler:
+    <<: *airflow-common
     command: scheduler
-
-  flower:
-    extends:
-      service: app
+    healthcheck:
+      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
+      interval: 10s
+      timeout: 10s
+      retries: 5
     restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+
+  airflow-worker:
+    <<: *airflow-common
+    command: celery worker
+    healthcheck:
+      test:
+        - "CMD-SHELL"
+        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    environment:
+      <<: *airflow-common-env
+      # Required to handle warm shutdown of the celery workers properly
+      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
+      DUMB_INIT_SETSID: "0"
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+
+  airflow-triggerer:
+    <<: *airflow-common
+    command: triggerer
+    healthcheck:
+      test: [ "CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"' ]
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+
+  airflow-init:
+    <<: *airflow-common
+    entrypoint: /bin/bash
+    # yamllint disable rule:line-length
+    command:
+      - -c
+      - |
+        function ver() {
+          printf "%04d%04d%04d%04d" $${1//./ }
+        }
+        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
+        airflow_version_comparable=$$(ver $${airflow_version})
+        min_airflow_version=2.2.0
+        min_airflow_version_comparable=$$(ver $${min_airflow_version})
+        if (( airflow_version_comparable < min_airflow_version_comparable )); then
+          echo
+          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
+          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
+          echo
+          exit 1
+        fi
+        if [[ -z "${AIRFLOW_UID}" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
+          echo "If you are on Linux, you SHOULD follow the instructions below to set "
+          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
+          echo "For other operating systems you can get rid of the warning with manually created .env file:"
+          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
+          echo
+        fi
+        one_meg=1048576
+        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
+        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
+        disk_available=$$(df / | tail -1 | awk '{print $$4}')
+        warning_resources="false"
+        if (( mem_available < 4000 )) ; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
+          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
+          echo
+          warning_resources="true"
+        fi
+        if (( cpus_available < 2 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
+          echo "At least 2 CPUs recommended. You have $${cpus_available}"
+          echo
+          warning_resources="true"
+        fi
+        if (( disk_available < one_meg * 10 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
+          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
+          echo
+          warning_resources="true"
+        fi
+        if [[ $${warning_resources} == "true" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
+          echo "Please follow the instructions to increase amount of resources available:"
+          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
+          echo
+        fi
+        mkdir -p /sources/logs /sources/dags /sources/plugins
+        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
+        exec /entrypoint airflow version
+    # yamllint enable rule:line-length
+    environment:
+      <<: *airflow-common-env
+      _AIRFLOW_DB_UPGRADE: 'true'
+      _AIRFLOW_WWW_USER_CREATE: 'true'
+      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
+      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
+      _PIP_ADDITIONAL_REQUIREMENTS: ''
+    user: "0:0"
+    volumes:
+      - .:/sources
+
+  airflow-cli:
+    <<: *airflow-common
+    profiles:
+      - debug
+    environment:
+      <<: *airflow-common-env
+      CONNECTION_CHECK_MAX_COUNT: "0"
+    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
+    command:
+      - bash
+      - -c
+      - airflow
+
+  # You can enable flower by adding "--profile flower" option e.g. docker-compose --profile flower up
+  # or by explicitly targeted on the command line e.g. docker-compose up flower.
+  # See: https://docs.docker.com/compose/profiles/
+  flower:
+    <<: *airflow-common
+    command: celery flower
+    profiles:
+      - flower
     ports:
-      - "5555:5555"
-    links:
-      - redis
-    command: flower
+      - 5555:5555
+    healthcheck:
+      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
